### ISSUE TITLE
first-and-last-0.1.0.0 can't compile its test suite with GHC 7.10.x

### ISSUE THREAD

**Issue by peti** [markandrus/first-and-last#1]
Citing from http://hydra.cryp.to/build/1337292/log/raw:

```
Preprocessing test suite 'Golden' for first-and-last-0.1.0.0...
[1 of 1] Compiling Golden           ( test/Golden.hs, dist/build/Golden.o )

test/Golden.hs:38:13: Warning:
    Defaulting the following constraint(s) to type ‘integer-gmp-1.0.0.0:GHC.Integer.Type.Integer’
      (Eq a0)
        arising from a use of ‘assertEqual’ at test/Golden.hs:38:13-23
      (GHC.Num.Num a0)
        arising from the literal ‘1’ at test/Golden.hs:39:28
      (Show a0)
        arising from a use of ‘assertEqual’ at test/Golden.hs:38:13-23
    In the expression:
      assertEqual (getFirst (foldMap pure [1, 2, 3, ....]), pure 1)
    In an equation for ‘firstTest’:
        firstTest
          = assertEqual (getFirst (foldMap pure [1, 2, ....]), pure 1)

test/Golden.hs:54:12: Warning:
    Defaulting the following constraint(s) to type ‘integer-gmp-1.0.0.0:GHC.Integer.Type.Integer’
      (Eq a0)
        arising from a use of ‘assertEqual’ at test/Golden.hs:54:12-22
      (GHC.Num.Num a0)
        arising from the literal ‘1’ at test/Golden.hs:55:27
      (Show a0)
        arising from a use of ‘assertEqual’ at test/Golden.hs:54:12-22
    In the expression:
      assertEqual (getLast (foldMap pure [1, 2, 3, ....]), pure 4)
    In an equation for ‘lastTest’:
        lastTest
          = assertEqual (getLast (foldMap pure [1, 2, ....]), pure 4)
In-place registering Golden-0.1.0.0...
[1 of 1] Compiling Main             ( dist/build/GoldenStub/GoldenStub-tmp/GoldenStub.hs, dist/build/GoldenStub/GoldenStub-tmp/Main.dyn_o )
Linking dist/build/GoldenStub/GoldenStub ...
ghc: panic! (the 'impossible' happened)
  (GHC version 7.10.2 for x86_64-unknown-linux):
    Don't understand library name Golden
```

This is a known issue in GHC. The only work-around I'm aware of is to rename the test suite.

**Comment by markandrus** [comment]
Hi @peti, thanks for the report. I have not seen this issue locally. Do you have steps I can follow to reproduce, and do you have GHC ticket I can track? Is it sufficient to rename `Golden` to either `Gold` or `Test`?

Also, what is hydra.cryp.to?

**Comment by peti** [comment]
Make sure to compile with `--enable-shared --enable-executable-dynamic`, then you should see the ICE locally, too.

The tickets https://github.com/haskell/cabal/issues/2039 and https://ghc.haskell.org/trac/ghc/ticket/9625 might be useful for further information.

`hydra.cryp.to` is a Continuous Integration system for NixOS. You'll find more information about that at http://nixos.org/.

**Comment by markandrus** [comment]
Thank you for the information, @peti; however, this is very frustrating: I have tried `Gold`, `Test`, and `Golden2` to no avail. I am considering removing the tests altogether.

**Comment by peti** [comment]
How about dropping the upper-case letter from the name?

**Comment by markandrus** [comment]
@peti that didn't work for me either, but i think i am going to switch to doctest. doctest appears to work.

**Comment by markandrus** [comment]
@peti can you please retry with http://hackage.haskell.org/package/first-and-last-0.1.0.1 ?

**Comment by peti** [comment]
The new version builds fine: http://hydra.cryp.to/job/nixpkgs/haskell-updates/haskellPackages.first-and-last.x86_64-linux. Thank you!
